# 预设动作

int32 value

# 抬手
int32 RAISE_HAND = 1001

# 挥手
int32 WAVE_HAND = 1002

# 握手
int32 SHAKE_HAND = 1003

# 飞吻
int32 FLYING_KISS_HAND = 1004

# 击掌
int32 CLAP_HAND = 1008

# 转身挥手
int32 TURN_WAVE_HAND = 2001

# 交互动作--鞠躬
int32 INTERACTION_BOW = 3001

# 交互动作--点赞
int32 INTERACTION_LIKE = 3002

# 交互动作--比YE
int32 INTERACTION_YE = 3003

# 交互动作--头顶比心
int32 INTERACTION_SWEATHEART = 3004

# 交互动作--敬礼
int32 SALUTE = 1013

# 交互动作--悲伤
int32 INTERACTION_SAD = 3006

# 交互动作--轻轻挥手
int32 INTERACTION_LIGHTWAVE = 3007

# 交互动作--拥抱
int32 INTERACTION_HUG = 3008

# 交互动作--胸前打叉
int32 INTERACTION_HANDX = 3009

# 交互动作--胸前挥手
int32 INTERACTION_CHESTWAVE = 3010

# 交互动作--加油
int32 INTERACTION_CHEER = 3011

# 交互动作--低空飞吻
int32 INTERACTION_BLOWKISS = 3012

# 交互动作--巴斯舞1
int32 INTERACTION_BASSDANCE1 = 3013

# 交互动作--巴斯舞2
int32 INTERACTION_BASSDANCE2 = 3014

# 交互动作--击掌
int32 HITCLAP = 3015

# 交互动作--说话手势
int32 INTERACTION_SPEAK = 3016

# 交互动作--碰拳
int32 CLIPFIST = 1009

# 交互动作--拍照姿势
int32 INTERACTION_PHOTOPOSTURE = 3018

# 交互动作--三连拍姿势
int32 INTERACTION_PHOTOTRIPPLEPOSTURE = 3019

# 头部动作--点头
int32 POINT_HEAD = 4001

# 头部动作--摇头
int32 SHAKE_HEAD = 4002