# ----------------------------------------------------
# request

# 请求头
CommonRequest request

---

# ----------------------------------------------------
# response

# 响应头
CommonResponse reponse

# 当前音量（0~100）
uint32 audio_volume