# ----------------------------------------------------
# request

# 请求头
CommonRequest request

# 请求静音状态
# true(mute)
# false(unmute)
bool is_mute

---

# ----------------------------------------------------
# response

# 响应头
CommonResponse reponse

# 当前静音状态
bool is_mute

